"""SAYC responder rebid (reresponse) rules."""

from .suit import (
    Accept2NTAfterMinorRaise,
    Accept3yJumpRaise,
    Accept3yJumpRaise3NT,
    AcceptGameTry,
    AcceptMinorInvite,
    AcceptQuantitative4NTMinor,
    AcceptReraise,
    Bid4MAfter3NTMedium,
    Bid4MAfterMax,
    Bid4MAfterShortness,
    Bid4MAfterSource,
    Blackwood4NTAfter3NTMedium,
    Blackwood4NTAfterJacoby4M,
    Blackwood4NTAfterJS,
    Blackwood4NTAfterMax,
    Blackwood4NTAfterShortness,
    Blackwood4NTAfterSource,
    BlackwoodResponseAfterLimitRaise,
    Decline2NTAfterMinorRaise,
    Decline3yJumpRaise,
    DeclineGameTry,
    DeclineMinorInvite,
    DeclineQuantitative4NTMinor,
    DeclineReraise,
    FourMAfter1NTRebid,
    FourMAfter2NTRebid,
    FourMAfter2Over1NewSuit,
    FourMAfter2Over1OwnSuit,
    FourMAfterJS,
    FourMAfterJumpRebid,
    FourMAfterJumpRebidOver1NT,
    FourMAfterNewSuit,
    FourMAfterOwnSuitMajor,
    FourMAfterRaise,
    FourMAfterRaise2Over1,
    FourthSuitAfter2Over1NS,
    FourthSuitAfterOwnSuit,
    FourthSuitForcing,
    GameInMinorAfterRaise,
    GFAfterReverse,
    GFRaiseReverseSuit,
    JumpInOwnSuitAfterReverse,
    JumpOwnMajorAfter1NT,
    JumpRebidAfter1NT,
    JumpRebidOwnSuitAfterNewSuit,
    JumpRebidOwnSuitAfterOwnSuit,
    NewSuitAfter1NTForcing,
    NewSuitAfter2Over1OwnSuit,
    NewSuitAt1Level,
    NewSuitForcingAfterMinorRaise,
    NewSuitForcingAfterOwnSuit,
    NewSuitWeakAfter1NT,
    OneNTReresponse,
    PassAfter1NTRebid,
    PassAfter2NTMinor3NT,
    PassAfter2NTOver1NT,
    PassAfter2NTRebid,
    PassAfter2Over1_2NT,
    PassAfter3NT2Over1,
    PassAfter3NTOver1NT,
    PassAfter3NTRebid,
    PassAfter3NTResponse,
    PassAfterAcceptedLimitRaise,
    PassAfterDoubleJumpRaise,
    PassAfterDoubleJumpRebid,
    PassAfterGame,
    PassAfterGameJumpOver1NT,
    PassAfterJacoby4M,
    PassAfterJumpRebid,
    PassAfterJumpRebidOver1NT,
    PassAfterMinor3NT,
    PassAfterMinorGame,
    PassAfterMinorRaise2Over1,
    PassAfterNewSuit,
    PassAfterNewSuit1NT,
    PassAfterRaise,
    PassAfterSuitRebid1NT,
    PreferenceAfter2Over1NS,
    PreferenceAfterOwnSuit,
    PreferenceAfterReverse,
    PreferenceAfterReverse2Over1,
    PreferenceAfterReverseOver1NT,
    PreferenceTo1stSuit1NT,
    PreferenceToOpenerFirst,
    Raise2ndSuitAfterMinorRaise,
    RaiseJumpShiftSuit,
    RaiseNewSuit1NTResponse,
    RaiseNewSuitInvite,
    RaiseOpenerAfter2Over1,
    RaiseOpenerNewSuit2Over1,
    RaiseReverseSuit,
    RaiseReverseSuit2Over1,
    RaiseReverseSuitOver1NT,
    RebidOwnAfter2Over1NS,
    RebidOwnAfterReverse2Over1,
    RebidOwnSuitAfter1NT,
    RebidOwnSuitAfter2Over1,
    RebidOwnSuitAfterJS,
    RebidOwnSuitAfterNewSuit,
    RebidOwnSuitAfterOwnSuit,
    RebidOwnSuitAfterReverse,
    ReturnToMinor,
    ReturnToOpenerSuitAfterJS1NT,
    ShowSecondSuitAfterJS,
    SlamTryMinorAfterRaise,
    SupportJumpShiftOver1NT,
    SupportOpenerFirstAfterJS,
    ThreeNTAfter1NTRebid,
    ThreeNTAfter2NTMinorMajor,
    ThreeNTAfter2NTMinorRebid,
    ThreeNTAfter2NTOver1NT,
    ThreeNTAfter2NTRebid,
    ThreeNTAfter2Over1_2NT,
    ThreeNTAfter2Over1NewSuit,
    ThreeNTAfter2Over1OwnSuit,
    ThreeNTAfterJSOver1NT,
    ThreeNTAfterJSReresponse,
    ThreeNTAfterJumpRebid,
    ThreeNTAfterJumpRebidNoStoppers,
    ThreeNTAfterJumpRebidOver1NT,
    ThreeNTAfterJumpShift,
    ThreeNTAfterMinorNewSuit,
    ThreeNTAfterNewSuit,
    ThreeNTAfterOwnSuit,
    ThreeNTAfterRaise,
    ThreeNTAfterRaise2Over1,
    ThreeNTAfterReverse,
    ThreeNTAfterReverse2Over1,
    ThreeNTAfterReverseOver1NT,
    ThreeSuitAfter2NTRebid,
    ThreeSuitAfter2Over1_2NT,
    ThreeXInviteAfterOwnSuit,
    ThreeYInviteAfterRaise,
    TwoNTAfter1NTRebid,
    TwoNTAfter2Over1,
    TwoNTAfter2Over1NS,
    TwoNTAfterNewSuit,
    TwoNTAfterOwnSuit,
    TwoNTAfterReverse,
    TwoNTAfterReverse2Over1,
    TwoNTAfterReverseOver1NT,
    WeakRaiseNewSuit,
)

__all__ = [
    # Section A: After raise of major
    "AcceptGameTry",
    "DeclineGameTry",
    "AcceptReraise",
    "DeclineReraise",
    "PassAfterGame",
    # Section B: After raise of minor
    "PassAfterMinor3NT",
    "Accept2NTAfterMinorRaise",
    "Decline2NTAfterMinorRaise",
    "ThreeNTAfterMinorNewSuit",
    "Raise2ndSuitAfterMinorRaise",
    "ReturnToMinor",
    "AcceptMinorInvite",
    "DeclineMinorInvite",
    "PassAfterMinorGame",
    # Section C-D: After limit raise
    "PassAfterAcceptedLimitRaise",
    "BlackwoodResponseAfterLimitRaise",
    # Section E: After Jacoby 2NT
    "Blackwood4NTAfterShortness",
    "Bid4MAfterShortness",
    "Blackwood4NTAfterSource",
    "Bid4MAfterSource",
    "Blackwood4NTAfterMax",
    "Bid4MAfterMax",
    "Blackwood4NTAfter3NTMedium",
    "Bid4MAfter3NTMedium",
    "Blackwood4NTAfterJacoby4M",
    "PassAfterJacoby4M",
    # Section F1: After 1NT rebid
    "ThreeNTAfter1NTRebid",
    "FourMAfter1NTRebid",
    "JumpOwnMajorAfter1NT",
    "NewSuitAfter1NTForcing",
    "TwoNTAfter1NTRebid",
    "JumpRebidAfter1NT",
    "NewSuitWeakAfter1NT",
    "RebidOwnSuitAfter1NT",
    "PassAfter1NTRebid",
    # Section F2: After raise
    "FourMAfterRaise",
    "ThreeNTAfterRaise",
    "ThreeYInviteAfterRaise",
    "PassAfterRaise",
    # Section F3: After jump raise
    "Accept3yJumpRaise",
    "Accept3yJumpRaise3NT",
    "Decline3yJumpRaise",
    # Section F4: After double jump raise
    "PassAfterDoubleJumpRaise",
    # Section F5: After opener rebid own suit
    "ThreeNTAfterOwnSuit",
    "FourMAfterOwnSuitMajor",
    "NewSuitForcingAfterOwnSuit",
    "FourthSuitAfterOwnSuit",
    "JumpRebidOwnSuitAfterOwnSuit",
    "TwoNTAfterOwnSuit",
    "ThreeXInviteAfterOwnSuit",
    "RebidOwnSuitAfterOwnSuit",
    "PreferenceAfterOwnSuit",
    # Section F6: After jump rebid
    "FourMAfterJumpRebid",
    "ThreeNTAfterJumpRebid",
    "ThreeNTAfterJumpRebidNoStoppers",
    "PassAfterJumpRebid",
    # Section F7: After new suit non-reverse
    "FourMAfterNewSuit",
    "ThreeNTAfterNewSuit",
    "FourthSuitForcing",
    "NewSuitForcingAfterMinorRaise",
    "RaiseNewSuitInvite",
    "JumpRebidOwnSuitAfterNewSuit",
    "TwoNTAfterNewSuit",
    "PreferenceToOpenerFirst",
    "RebidOwnSuitAfterNewSuit",
    "PassAfterNewSuit",
    # Section F7b: After 1-level new suit rebid
    "NewSuitAt1Level",
    "WeakRaiseNewSuit",
    "OneNTReresponse",
    # Section F8: After reverse
    "GFRaiseReverseSuit",
    "ThreeNTAfterReverse",
    "GFAfterReverse",
    "RaiseReverseSuit",
    "JumpInOwnSuitAfterReverse",
    "TwoNTAfterReverse",
    "RebidOwnSuitAfterReverse",
    "PreferenceAfterReverse",
    # Section F9: After jump shift
    "RaiseJumpShiftSuit",
    "SupportOpenerFirstAfterJS",
    "RebidOwnSuitAfterJS",
    "ThreeNTAfterJumpShift",
    # Section F10: After 2NT rebid
    "FourMAfter2NTRebid",
    "ThreeNTAfter2NTRebid",
    "ThreeSuitAfter2NTRebid",
    "PassAfter2NTRebid",
    # Section F11: After 3NT rebid
    "PassAfter3NTRebid",
    # Section F12: After double-jump rebid own suit
    "PassAfterDoubleJumpRebid",
    # Section G: After 1NT response
    "PassAfterSuitRebid1NT",
    "RaiseNewSuit1NTResponse",
    "PreferenceTo1stSuit1NT",
    "PassAfterNewSuit1NT",
    "ThreeNTAfter2NTOver1NT",
    "PassAfter2NTOver1NT",
    "FourMAfterJumpRebidOver1NT",
    "ThreeNTAfterJumpRebidOver1NT",
    "PassAfterJumpRebidOver1NT",
    "PassAfter3NTOver1NT",
    "SupportJumpShiftOver1NT",
    "ReturnToOpenerSuitAfterJS1NT",
    "ThreeNTAfterJSOver1NT",
    "ThreeNTAfterReverseOver1NT",
    "RaiseReverseSuitOver1NT",
    "PreferenceAfterReverseOver1NT",
    "TwoNTAfterReverseOver1NT",
    "PassAfterGameJumpOver1NT",
    # Section H1: After raise (2-over-1)
    "ThreeNTAfterRaise2Over1",
    "FourMAfterRaise2Over1",
    "SlamTryMinorAfterRaise",
    "GameInMinorAfterRaise",
    "PassAfterMinorRaise2Over1",
    # Section H2: After rebid own suit (2-over-1)
    "FourMAfter2Over1OwnSuit",
    "ThreeNTAfter2Over1OwnSuit",
    "NewSuitAfter2Over1OwnSuit",
    "RaiseOpenerAfter2Over1",
    "RebidOwnSuitAfter2Over1",
    "TwoNTAfter2Over1",
    # Section H3: After new suit non-reverse (2-over-1)
    "FourMAfter2Over1NewSuit",
    "ThreeNTAfter2Over1NewSuit",
    "FourthSuitAfter2Over1NS",
    "RaiseOpenerNewSuit2Over1",
    "PreferenceAfter2Over1NS",
    "RebidOwnAfter2Over1NS",
    "TwoNTAfter2Over1NS",
    # Section H4: After 2NT (2-over-1)
    "ThreeNTAfter2Over1_2NT",
    "ThreeSuitAfter2Over1_2NT",
    "PassAfter2Over1_2NT",
    # Section H5: After reverse (2-over-1)
    "ThreeNTAfterReverse2Over1",
    "RaiseReverseSuit2Over1",
    "RebidOwnAfterReverse2Over1",
    "PreferenceAfterReverse2Over1",
    "TwoNTAfterReverse2Over1",
    # Section H6: After 3NT (2-over-1)
    "PassAfter3NT2Over1",
    # Section I: After jump shift
    "Blackwood4NTAfterJS",
    "FourMAfterJS",
    "ShowSecondSuitAfterJS",
    "ThreeNTAfterJSReresponse",
    # Section J: After 2NT over minor
    "AcceptQuantitative4NTMinor",
    "DeclineQuantitative4NTMinor",
    "ThreeNTAfter2NTMinorMajor",
    "ThreeNTAfter2NTMinorRebid",
    "PassAfter2NTMinor3NT",
    # Section K: After 3NT response
    "PassAfter3NTResponse",
]
